#!/bin/bash
# Representative example of the script generated by xtbsetup.sh;
# the exact contents depend on the version of the setup script on ACME.
#SBATCH -J pentene-xtb
#SBATCH -p normal
#SBATCH -t 12:00:00
#SBATCH -N 1
#SBATCH --export=NONE
#SBATCH --ntasks-per-node 1

ulimit -s unlimited
export OMP_STACKSIZE=1G
export OMP_NUM_THREADS=1,1
export OMP_MAX_ACTIVE_LEVELS=1
export MKL_NUM_THREADS=1

xtb pentene.xyz --opt -c 0 -P 1 > xtb.out
