#!/bin/bash
# Representative example of the script generated by crestsetup.sh;
# the exact contents depend on the version of the setup script on ACME.
#SBATCH -J pentene-crest
#SBATCH -p normal
#SBATCH -t 12:00:00
#SBATCH -N 1
#SBATCH --export=NONE
#SBATCH --ntasks-per-node 32

ulimit -s unlimited
export OMP_STACKSIZE=1G
export OMP_NUM_THREADS=32,1
export OMP_MAX_ACTIVE_LEVELS=1
export MKL_NUM_THREADS=32

crest xtbopt.xyz -chrg 0 -T 32 > crest.out
