#!/bin/bash
# Representative example of the script generated by censosetup.sh;
# the exact contents depend on the version of the setup script on ACME.
#SBATCH -J pentene-censo
#SBATCH -p normal
#SBATCH -t 12:00:00
#SBATCH -N 1
#SBATCH --export=NONE
#SBATCH --ntasks-per-node 32

ulimit -s unlimited
export OMP_STACKSIZE=1G
export OMP_NUM_THREADS=32,1
export OMP_MAX_ACTIVE_LEVELS=1
export MKL_NUM_THREADS=32

export PYTHONUNBUFFERED=1

# CENSO 1.x command-line syntax
censo -inp crest_conformers.xyz -chrg 0 -P 4 -O 8 > censo.out
